auto_docking:
  differential_drive: True
  kp:
    # x:           0.3
    x:           0.6 # Differential drive - CAUTION: PLEASE DO NOT GIVE HIGH VALUES. It might make the robot go at very high speed.
    y:           1.5
    theta:       0.5
    x_fine:      0.5
    y_fine:      3.0
    theta_fine:  0.2
  velocity:
    linear:
      x:
        max:     0.03
        min:     0
      y:
        max:     0.05
        min:     0
    angular:
        min:     0
  tolerance:
    y:           0.003
