auto_docking:
  differential_drive: True
  max_vel_limit: 0.035 # Irrespective of the magnitude for the final stage of docking. 
  undocking_pose: 0.5 # This is the minimum safest distance for the robot to perform operation outside the safety region of the docking station. 
  kp:
    x:           0.6
    y:           1.5
    theta:       0.5
    x_fine:      0.5
    y_fine:      3.0
    theta_fine:  0.2
  velocity:
    linear:
      x:
        max:     0.03
        min:     0
      y:
        max:     0.05
        min:     0
    angular:
        min:     0
  tolerance:
    y:           0.003
